#!/bin/bash
echo "=== 验证使用日志记录情况 ==="
echo ""
echo "1. 检查最近的使用日志记录："
echo "   SELECT id, user_id, api_key_id, temp_api_key_id, model, input_tokens, output_tokens, created_at"
echo "   FROM usage_logs"
echo "   ORDER BY created_at DESC"
echo "   LIMIT 5;"
echo ""
echo "2. 检查特定 API Key 的使用统计："
echo "   SELECT "
echo "     COUNT(*) as total_requests,"
echo "     SUM(input_tokens + output_tokens) as total_tokens,"
echo "     MAX(created_at) as last_used_at"
echo "   FROM usage_logs"
echo "   WHERE api_key_id = <YOUR_API_KEY_ID>;"
echo ""
echo "3. 检查临时密钥的使用统计："
echo "   SELECT "
echo "     COUNT(*) as total_requests,"
echo "     SUM(input_tokens + output_tokens) as total_tokens,"
echo "     MAX(created_at) as last_used_at"
echo "   FROM usage_logs"
echo "   WHERE temp_api_key_id = <YOUR_TEMP_KEY_ID>;"
