// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/tempapikey"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TempAPIKeyUpdate is the builder for updating TempAPIKey entities.
type TempAPIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *TempAPIKeyMutation
}

// Where appends a list predicates to the TempAPIKeyUpdate builder.
func (_u *TempAPIKeyUpdate) Where(ps ...predicate.TempAPIKey) *TempAPIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TempAPIKeyUpdate) SetUpdatedAt(v time.Time) *TempAPIKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TempAPIKeyUpdate) SetDeletedAt(v time.Time) *TempAPIKeyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableDeletedAt(v *time.Time) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TempAPIKeyUpdate) ClearDeletedAt() *TempAPIKeyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetKey sets the "key" field.
func (_u *TempAPIKeyUpdate) SetKey(v string) *TempAPIKeyUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableKey(v *string) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TempAPIKeyUpdate) SetName(v string) *TempAPIKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableName(v *string) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *TempAPIKeyUpdate) SetGroupID(v int64) *TempAPIKeyUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableGroupID(v *int64) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetValidDays sets the "valid_days" field.
func (_u *TempAPIKeyUpdate) SetValidDays(v int) *TempAPIKeyUpdate {
	_u.mutation.ResetValidDays()
	_u.mutation.SetValidDays(v)
	return _u
}

// SetNillableValidDays sets the "valid_days" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableValidDays(v *int) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetValidDays(*v)
	}
	return _u
}

// AddValidDays adds value to the "valid_days" field.
func (_u *TempAPIKeyUpdate) AddValidDays(v int) *TempAPIKeyUpdate {
	_u.mutation.AddValidDays(v)
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *TempAPIKeyUpdate) SetActivatedAt(v time.Time) *TempAPIKeyUpdate {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableActivatedAt(v *time.Time) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *TempAPIKeyUpdate) ClearActivatedAt() *TempAPIKeyUpdate {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TempAPIKeyUpdate) SetExpiresAt(v time.Time) *TempAPIKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableExpiresAt(v *time.Time) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TempAPIKeyUpdate) ClearExpiresAt() *TempAPIKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDailyLimit sets the "daily_limit" field.
func (_u *TempAPIKeyUpdate) SetDailyLimit(v int) *TempAPIKeyUpdate {
	_u.mutation.ResetDailyLimit()
	_u.mutation.SetDailyLimit(v)
	return _u
}

// SetNillableDailyLimit sets the "daily_limit" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableDailyLimit(v *int) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetDailyLimit(*v)
	}
	return _u
}

// AddDailyLimit adds value to the "daily_limit" field.
func (_u *TempAPIKeyUpdate) AddDailyLimit(v int) *TempAPIKeyUpdate {
	_u.mutation.AddDailyLimit(v)
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *TempAPIKeyUpdate) SetCurrentPeriodStart(v time.Time) *TempAPIKeyUpdate {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableCurrentPeriodStart(v *time.Time) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (_u *TempAPIKeyUpdate) ClearCurrentPeriodStart() *TempAPIKeyUpdate {
	_u.mutation.ClearCurrentPeriodStart()
	return _u
}

// SetCurrentPeriodCount sets the "current_period_count" field.
func (_u *TempAPIKeyUpdate) SetCurrentPeriodCount(v int) *TempAPIKeyUpdate {
	_u.mutation.ResetCurrentPeriodCount()
	_u.mutation.SetCurrentPeriodCount(v)
	return _u
}

// SetNillableCurrentPeriodCount sets the "current_period_count" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableCurrentPeriodCount(v *int) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetCurrentPeriodCount(*v)
	}
	return _u
}

// AddCurrentPeriodCount adds value to the "current_period_count" field.
func (_u *TempAPIKeyUpdate) AddCurrentPeriodCount(v int) *TempAPIKeyUpdate {
	_u.mutation.AddCurrentPeriodCount(v)
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *TempAPIKeyUpdate) SetTotalRequests(v int64) *TempAPIKeyUpdate {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableTotalRequests(v *int64) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *TempAPIKeyUpdate) AddTotalRequests(v int64) *TempAPIKeyUpdate {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TempAPIKeyUpdate) SetStatus(v string) *TempAPIKeyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableStatus(v *string) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TempAPIKeyUpdate) SetCreatedBy(v int64) *TempAPIKeyUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TempAPIKeyUpdate) SetNillableCreatedBy(v *int64) *TempAPIKeyUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *TempAPIKeyUpdate) SetGroup(v *Group) *TempAPIKeyUpdate {
	return _u.SetGroupID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TempAPIKeyUpdate) SetCreatorID(id int64) *TempAPIKeyUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TempAPIKeyUpdate) SetCreator(v *User) *TempAPIKeyUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *TempAPIKeyUpdate) AddUsageLogIDs(ids ...int64) *TempAPIKeyUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *TempAPIKeyUpdate) AddUsageLogs(v ...*UsageLog) *TempAPIKeyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the TempAPIKeyMutation object of the builder.
func (_u *TempAPIKeyUpdate) Mutation() *TempAPIKeyMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *TempAPIKeyUpdate) ClearGroup() *TempAPIKeyUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TempAPIKeyUpdate) ClearCreator() *TempAPIKeyUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *TempAPIKeyUpdate) ClearUsageLogs() *TempAPIKeyUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *TempAPIKeyUpdate) RemoveUsageLogIDs(ids ...int64) *TempAPIKeyUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *TempAPIKeyUpdate) RemoveUsageLogs(v ...*UsageLog) *TempAPIKeyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TempAPIKeyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TempAPIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TempAPIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TempAPIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TempAPIKeyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if tempapikey.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized tempapikey.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := tempapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TempAPIKeyUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tempapikey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TempAPIKey.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := tempapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TempAPIKey.name": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TempAPIKey.group"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TempAPIKey.creator"`)
	}
	return nil
}

func (_u *TempAPIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tempapikey.Table, tempapikey.Columns, sqlgraph.NewFieldSpec(tempapikey.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tempapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tempapikey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tempapikey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tempapikey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tempapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidDays(); ok {
		_spec.SetField(tempapikey.FieldValidDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidDays(); ok {
		_spec.AddField(tempapikey.FieldValidDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(tempapikey.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(tempapikey.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(tempapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(tempapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DailyLimit(); ok {
		_spec.SetField(tempapikey.FieldDailyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDailyLimit(); ok {
		_spec.AddField(tempapikey.FieldDailyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(tempapikey.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodStartCleared() {
		_spec.ClearField(tempapikey.FieldCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPeriodCount(); ok {
		_spec.SetField(tempapikey.FieldCurrentPeriodCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentPeriodCount(); ok {
		_spec.AddField(tempapikey.FieldCurrentPeriodCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(tempapikey.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(tempapikey.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tempapikey.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.GroupTable,
			Columns: []string{tempapikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.GroupTable,
			Columns: []string{tempapikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.CreatorTable,
			Columns: []string{tempapikey.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.CreatorTable,
			Columns: []string{tempapikey.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tempapikey.UsageLogsTable,
			Columns: []string{tempapikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tempapikey.UsageLogsTable,
			Columns: []string{tempapikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tempapikey.UsageLogsTable,
			Columns: []string{tempapikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tempapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TempAPIKeyUpdateOne is the builder for updating a single TempAPIKey entity.
type TempAPIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TempAPIKeyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TempAPIKeyUpdateOne) SetUpdatedAt(v time.Time) *TempAPIKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TempAPIKeyUpdateOne) SetDeletedAt(v time.Time) *TempAPIKeyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableDeletedAt(v *time.Time) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TempAPIKeyUpdateOne) ClearDeletedAt() *TempAPIKeyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetKey sets the "key" field.
func (_u *TempAPIKeyUpdateOne) SetKey(v string) *TempAPIKeyUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableKey(v *string) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TempAPIKeyUpdateOne) SetName(v string) *TempAPIKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableName(v *string) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *TempAPIKeyUpdateOne) SetGroupID(v int64) *TempAPIKeyUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableGroupID(v *int64) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetValidDays sets the "valid_days" field.
func (_u *TempAPIKeyUpdateOne) SetValidDays(v int) *TempAPIKeyUpdateOne {
	_u.mutation.ResetValidDays()
	_u.mutation.SetValidDays(v)
	return _u
}

// SetNillableValidDays sets the "valid_days" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableValidDays(v *int) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetValidDays(*v)
	}
	return _u
}

// AddValidDays adds value to the "valid_days" field.
func (_u *TempAPIKeyUpdateOne) AddValidDays(v int) *TempAPIKeyUpdateOne {
	_u.mutation.AddValidDays(v)
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *TempAPIKeyUpdateOne) SetActivatedAt(v time.Time) *TempAPIKeyUpdateOne {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableActivatedAt(v *time.Time) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *TempAPIKeyUpdateOne) ClearActivatedAt() *TempAPIKeyUpdateOne {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TempAPIKeyUpdateOne) SetExpiresAt(v time.Time) *TempAPIKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TempAPIKeyUpdateOne) ClearExpiresAt() *TempAPIKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDailyLimit sets the "daily_limit" field.
func (_u *TempAPIKeyUpdateOne) SetDailyLimit(v int) *TempAPIKeyUpdateOne {
	_u.mutation.ResetDailyLimit()
	_u.mutation.SetDailyLimit(v)
	return _u
}

// SetNillableDailyLimit sets the "daily_limit" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableDailyLimit(v *int) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetDailyLimit(*v)
	}
	return _u
}

// AddDailyLimit adds value to the "daily_limit" field.
func (_u *TempAPIKeyUpdateOne) AddDailyLimit(v int) *TempAPIKeyUpdateOne {
	_u.mutation.AddDailyLimit(v)
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *TempAPIKeyUpdateOne) SetCurrentPeriodStart(v time.Time) *TempAPIKeyUpdateOne {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableCurrentPeriodStart(v *time.Time) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (_u *TempAPIKeyUpdateOne) ClearCurrentPeriodStart() *TempAPIKeyUpdateOne {
	_u.mutation.ClearCurrentPeriodStart()
	return _u
}

// SetCurrentPeriodCount sets the "current_period_count" field.
func (_u *TempAPIKeyUpdateOne) SetCurrentPeriodCount(v int) *TempAPIKeyUpdateOne {
	_u.mutation.ResetCurrentPeriodCount()
	_u.mutation.SetCurrentPeriodCount(v)
	return _u
}

// SetNillableCurrentPeriodCount sets the "current_period_count" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableCurrentPeriodCount(v *int) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodCount(*v)
	}
	return _u
}

// AddCurrentPeriodCount adds value to the "current_period_count" field.
func (_u *TempAPIKeyUpdateOne) AddCurrentPeriodCount(v int) *TempAPIKeyUpdateOne {
	_u.mutation.AddCurrentPeriodCount(v)
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *TempAPIKeyUpdateOne) SetTotalRequests(v int64) *TempAPIKeyUpdateOne {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableTotalRequests(v *int64) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *TempAPIKeyUpdateOne) AddTotalRequests(v int64) *TempAPIKeyUpdateOne {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TempAPIKeyUpdateOne) SetStatus(v string) *TempAPIKeyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableStatus(v *string) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TempAPIKeyUpdateOne) SetCreatedBy(v int64) *TempAPIKeyUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TempAPIKeyUpdateOne) SetNillableCreatedBy(v *int64) *TempAPIKeyUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *TempAPIKeyUpdateOne) SetGroup(v *Group) *TempAPIKeyUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TempAPIKeyUpdateOne) SetCreatorID(id int64) *TempAPIKeyUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TempAPIKeyUpdateOne) SetCreator(v *User) *TempAPIKeyUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *TempAPIKeyUpdateOne) AddUsageLogIDs(ids ...int64) *TempAPIKeyUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *TempAPIKeyUpdateOne) AddUsageLogs(v ...*UsageLog) *TempAPIKeyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the TempAPIKeyMutation object of the builder.
func (_u *TempAPIKeyUpdateOne) Mutation() *TempAPIKeyMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *TempAPIKeyUpdateOne) ClearGroup() *TempAPIKeyUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TempAPIKeyUpdateOne) ClearCreator() *TempAPIKeyUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *TempAPIKeyUpdateOne) ClearUsageLogs() *TempAPIKeyUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *TempAPIKeyUpdateOne) RemoveUsageLogIDs(ids ...int64) *TempAPIKeyUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *TempAPIKeyUpdateOne) RemoveUsageLogs(v ...*UsageLog) *TempAPIKeyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the TempAPIKeyUpdate builder.
func (_u *TempAPIKeyUpdateOne) Where(ps ...predicate.TempAPIKey) *TempAPIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TempAPIKeyUpdateOne) Select(field string, fields ...string) *TempAPIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TempAPIKey entity.
func (_u *TempAPIKeyUpdateOne) Save(ctx context.Context) (*TempAPIKey, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TempAPIKeyUpdateOne) SaveX(ctx context.Context) *TempAPIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TempAPIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TempAPIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TempAPIKeyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if tempapikey.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized tempapikey.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := tempapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TempAPIKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tempapikey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TempAPIKey.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := tempapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TempAPIKey.name": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TempAPIKey.group"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TempAPIKey.creator"`)
	}
	return nil
}

func (_u *TempAPIKeyUpdateOne) sqlSave(ctx context.Context) (_node *TempAPIKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tempapikey.Table, tempapikey.Columns, sqlgraph.NewFieldSpec(tempapikey.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TempAPIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tempapikey.FieldID)
		for _, f := range fields {
			if !tempapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tempapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tempapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tempapikey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tempapikey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tempapikey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tempapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidDays(); ok {
		_spec.SetField(tempapikey.FieldValidDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidDays(); ok {
		_spec.AddField(tempapikey.FieldValidDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(tempapikey.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(tempapikey.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(tempapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(tempapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DailyLimit(); ok {
		_spec.SetField(tempapikey.FieldDailyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDailyLimit(); ok {
		_spec.AddField(tempapikey.FieldDailyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(tempapikey.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodStartCleared() {
		_spec.ClearField(tempapikey.FieldCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPeriodCount(); ok {
		_spec.SetField(tempapikey.FieldCurrentPeriodCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentPeriodCount(); ok {
		_spec.AddField(tempapikey.FieldCurrentPeriodCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(tempapikey.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(tempapikey.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tempapikey.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.GroupTable,
			Columns: []string{tempapikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.GroupTable,
			Columns: []string{tempapikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.CreatorTable,
			Columns: []string{tempapikey.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.CreatorTable,
			Columns: []string{tempapikey.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tempapikey.UsageLogsTable,
			Columns: []string{tempapikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tempapikey.UsageLogsTable,
			Columns: []string{tempapikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tempapikey.UsageLogsTable,
			Columns: []string{tempapikey.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TempAPIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tempapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
