// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/tempapikey"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TempAPIKeyCreate is the builder for creating a TempAPIKey entity.
type TempAPIKeyCreate struct {
	config
	mutation *TempAPIKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TempAPIKeyCreate) SetCreatedAt(v time.Time) *TempAPIKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableCreatedAt(v *time.Time) *TempAPIKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TempAPIKeyCreate) SetUpdatedAt(v time.Time) *TempAPIKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableUpdatedAt(v *time.Time) *TempAPIKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TempAPIKeyCreate) SetDeletedAt(v time.Time) *TempAPIKeyCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableDeletedAt(v *time.Time) *TempAPIKeyCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *TempAPIKeyCreate) SetKey(v string) *TempAPIKeyCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TempAPIKeyCreate) SetName(v string) *TempAPIKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *TempAPIKeyCreate) SetGroupID(v int64) *TempAPIKeyCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetValidDays sets the "valid_days" field.
func (_c *TempAPIKeyCreate) SetValidDays(v int) *TempAPIKeyCreate {
	_c.mutation.SetValidDays(v)
	return _c
}

// SetNillableValidDays sets the "valid_days" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableValidDays(v *int) *TempAPIKeyCreate {
	if v != nil {
		_c.SetValidDays(*v)
	}
	return _c
}

// SetActivatedAt sets the "activated_at" field.
func (_c *TempAPIKeyCreate) SetActivatedAt(v time.Time) *TempAPIKeyCreate {
	_c.mutation.SetActivatedAt(v)
	return _c
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableActivatedAt(v *time.Time) *TempAPIKeyCreate {
	if v != nil {
		_c.SetActivatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TempAPIKeyCreate) SetExpiresAt(v time.Time) *TempAPIKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableExpiresAt(v *time.Time) *TempAPIKeyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetDailyLimit sets the "daily_limit" field.
func (_c *TempAPIKeyCreate) SetDailyLimit(v int) *TempAPIKeyCreate {
	_c.mutation.SetDailyLimit(v)
	return _c
}

// SetNillableDailyLimit sets the "daily_limit" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableDailyLimit(v *int) *TempAPIKeyCreate {
	if v != nil {
		_c.SetDailyLimit(*v)
	}
	return _c
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_c *TempAPIKeyCreate) SetCurrentPeriodStart(v time.Time) *TempAPIKeyCreate {
	_c.mutation.SetCurrentPeriodStart(v)
	return _c
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableCurrentPeriodStart(v *time.Time) *TempAPIKeyCreate {
	if v != nil {
		_c.SetCurrentPeriodStart(*v)
	}
	return _c
}

// SetCurrentPeriodCount sets the "current_period_count" field.
func (_c *TempAPIKeyCreate) SetCurrentPeriodCount(v int) *TempAPIKeyCreate {
	_c.mutation.SetCurrentPeriodCount(v)
	return _c
}

// SetNillableCurrentPeriodCount sets the "current_period_count" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableCurrentPeriodCount(v *int) *TempAPIKeyCreate {
	if v != nil {
		_c.SetCurrentPeriodCount(*v)
	}
	return _c
}

// SetTotalRequests sets the "total_requests" field.
func (_c *TempAPIKeyCreate) SetTotalRequests(v int64) *TempAPIKeyCreate {
	_c.mutation.SetTotalRequests(v)
	return _c
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableTotalRequests(v *int64) *TempAPIKeyCreate {
	if v != nil {
		_c.SetTotalRequests(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TempAPIKeyCreate) SetStatus(v string) *TempAPIKeyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TempAPIKeyCreate) SetNillableStatus(v *string) *TempAPIKeyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *TempAPIKeyCreate) SetCreatedBy(v int64) *TempAPIKeyCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *TempAPIKeyCreate) SetGroup(v *Group) *TempAPIKeyCreate {
	return _c.SetGroupID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *TempAPIKeyCreate) SetCreatorID(id int64) *TempAPIKeyCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *TempAPIKeyCreate) SetCreator(v *User) *TempAPIKeyCreate {
	return _c.SetCreatorID(v.ID)
}

// Mutation returns the TempAPIKeyMutation object of the builder.
func (_c *TempAPIKeyCreate) Mutation() *TempAPIKeyMutation {
	return _c.mutation
}

// Save creates the TempAPIKey in the database.
func (_c *TempAPIKeyCreate) Save(ctx context.Context) (*TempAPIKey, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TempAPIKeyCreate) SaveX(ctx context.Context) *TempAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TempAPIKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TempAPIKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TempAPIKeyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if tempapikey.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized tempapikey.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := tempapikey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if tempapikey.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized tempapikey.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := tempapikey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ValidDays(); !ok {
		v := tempapikey.DefaultValidDays
		_c.mutation.SetValidDays(v)
	}
	if _, ok := _c.mutation.DailyLimit(); !ok {
		v := tempapikey.DefaultDailyLimit
		_c.mutation.SetDailyLimit(v)
	}
	if _, ok := _c.mutation.CurrentPeriodCount(); !ok {
		v := tempapikey.DefaultCurrentPeriodCount
		_c.mutation.SetCurrentPeriodCount(v)
	}
	if _, ok := _c.mutation.TotalRequests(); !ok {
		v := tempapikey.DefaultTotalRequests
		_c.mutation.SetTotalRequests(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := tempapikey.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TempAPIKeyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TempAPIKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TempAPIKey.updated_at"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "TempAPIKey.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := tempapikey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TempAPIKey.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TempAPIKey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := tempapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TempAPIKey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "TempAPIKey.group_id"`)}
	}
	if _, ok := _c.mutation.ValidDays(); !ok {
		return &ValidationError{Name: "valid_days", err: errors.New(`ent: missing required field "TempAPIKey.valid_days"`)}
	}
	if _, ok := _c.mutation.DailyLimit(); !ok {
		return &ValidationError{Name: "daily_limit", err: errors.New(`ent: missing required field "TempAPIKey.daily_limit"`)}
	}
	if _, ok := _c.mutation.CurrentPeriodCount(); !ok {
		return &ValidationError{Name: "current_period_count", err: errors.New(`ent: missing required field "TempAPIKey.current_period_count"`)}
	}
	if _, ok := _c.mutation.TotalRequests(); !ok {
		return &ValidationError{Name: "total_requests", err: errors.New(`ent: missing required field "TempAPIKey.total_requests"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TempAPIKey.status"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "TempAPIKey.created_by"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "TempAPIKey.group"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "TempAPIKey.creator"`)}
	}
	return nil
}

func (_c *TempAPIKeyCreate) sqlSave(ctx context.Context) (*TempAPIKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TempAPIKeyCreate) createSpec() (*TempAPIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &TempAPIKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tempapikey.Table, sqlgraph.NewFieldSpec(tempapikey.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tempapikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tempapikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(tempapikey.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(tempapikey.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tempapikey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ValidDays(); ok {
		_spec.SetField(tempapikey.FieldValidDays, field.TypeInt, value)
		_node.ValidDays = value
	}
	if value, ok := _c.mutation.ActivatedAt(); ok {
		_spec.SetField(tempapikey.FieldActivatedAt, field.TypeTime, value)
		_node.ActivatedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(tempapikey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.DailyLimit(); ok {
		_spec.SetField(tempapikey.FieldDailyLimit, field.TypeInt, value)
		_node.DailyLimit = value
	}
	if value, ok := _c.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(tempapikey.FieldCurrentPeriodStart, field.TypeTime, value)
		_node.CurrentPeriodStart = &value
	}
	if value, ok := _c.mutation.CurrentPeriodCount(); ok {
		_spec.SetField(tempapikey.FieldCurrentPeriodCount, field.TypeInt, value)
		_node.CurrentPeriodCount = value
	}
	if value, ok := _c.mutation.TotalRequests(); ok {
		_spec.SetField(tempapikey.FieldTotalRequests, field.TypeInt64, value)
		_node.TotalRequests = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tempapikey.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.GroupTable,
			Columns: []string{tempapikey.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tempapikey.CreatorTable,
			Columns: []string{tempapikey.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TempAPIKey.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TempAPIKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TempAPIKeyCreate) OnConflict(opts ...sql.ConflictOption) *TempAPIKeyUpsertOne {
	_c.conflict = opts
	return &TempAPIKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TempAPIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TempAPIKeyCreate) OnConflictColumns(columns ...string) *TempAPIKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TempAPIKeyUpsertOne{
		create: _c,
	}
}

type (
	// TempAPIKeyUpsertOne is the builder for "upsert"-ing
	//  one TempAPIKey node.
	TempAPIKeyUpsertOne struct {
		create *TempAPIKeyCreate
	}

	// TempAPIKeyUpsert is the "OnConflict" setter.
	TempAPIKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TempAPIKeyUpsert) SetUpdatedAt(v time.Time) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateUpdatedAt() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TempAPIKeyUpsert) SetDeletedAt(v time.Time) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateDeletedAt() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TempAPIKeyUpsert) ClearDeletedAt() *TempAPIKeyUpsert {
	u.SetNull(tempapikey.FieldDeletedAt)
	return u
}

// SetKey sets the "key" field.
func (u *TempAPIKeyUpsert) SetKey(v string) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateKey() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldKey)
	return u
}

// SetName sets the "name" field.
func (u *TempAPIKeyUpsert) SetName(v string) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateName() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldName)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *TempAPIKeyUpsert) SetGroupID(v int64) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateGroupID() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldGroupID)
	return u
}

// SetValidDays sets the "valid_days" field.
func (u *TempAPIKeyUpsert) SetValidDays(v int) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldValidDays, v)
	return u
}

// UpdateValidDays sets the "valid_days" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateValidDays() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldValidDays)
	return u
}

// AddValidDays adds v to the "valid_days" field.
func (u *TempAPIKeyUpsert) AddValidDays(v int) *TempAPIKeyUpsert {
	u.Add(tempapikey.FieldValidDays, v)
	return u
}

// SetActivatedAt sets the "activated_at" field.
func (u *TempAPIKeyUpsert) SetActivatedAt(v time.Time) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldActivatedAt, v)
	return u
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateActivatedAt() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldActivatedAt)
	return u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *TempAPIKeyUpsert) ClearActivatedAt() *TempAPIKeyUpsert {
	u.SetNull(tempapikey.FieldActivatedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *TempAPIKeyUpsert) SetExpiresAt(v time.Time) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateExpiresAt() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *TempAPIKeyUpsert) ClearExpiresAt() *TempAPIKeyUpsert {
	u.SetNull(tempapikey.FieldExpiresAt)
	return u
}

// SetDailyLimit sets the "daily_limit" field.
func (u *TempAPIKeyUpsert) SetDailyLimit(v int) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldDailyLimit, v)
	return u
}

// UpdateDailyLimit sets the "daily_limit" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateDailyLimit() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldDailyLimit)
	return u
}

// AddDailyLimit adds v to the "daily_limit" field.
func (u *TempAPIKeyUpsert) AddDailyLimit(v int) *TempAPIKeyUpsert {
	u.Add(tempapikey.FieldDailyLimit, v)
	return u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *TempAPIKeyUpsert) SetCurrentPeriodStart(v time.Time) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldCurrentPeriodStart, v)
	return u
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateCurrentPeriodStart() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldCurrentPeriodStart)
	return u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (u *TempAPIKeyUpsert) ClearCurrentPeriodStart() *TempAPIKeyUpsert {
	u.SetNull(tempapikey.FieldCurrentPeriodStart)
	return u
}

// SetCurrentPeriodCount sets the "current_period_count" field.
func (u *TempAPIKeyUpsert) SetCurrentPeriodCount(v int) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldCurrentPeriodCount, v)
	return u
}

// UpdateCurrentPeriodCount sets the "current_period_count" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateCurrentPeriodCount() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldCurrentPeriodCount)
	return u
}

// AddCurrentPeriodCount adds v to the "current_period_count" field.
func (u *TempAPIKeyUpsert) AddCurrentPeriodCount(v int) *TempAPIKeyUpsert {
	u.Add(tempapikey.FieldCurrentPeriodCount, v)
	return u
}

// SetTotalRequests sets the "total_requests" field.
func (u *TempAPIKeyUpsert) SetTotalRequests(v int64) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldTotalRequests, v)
	return u
}

// UpdateTotalRequests sets the "total_requests" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateTotalRequests() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldTotalRequests)
	return u
}

// AddTotalRequests adds v to the "total_requests" field.
func (u *TempAPIKeyUpsert) AddTotalRequests(v int64) *TempAPIKeyUpsert {
	u.Add(tempapikey.FieldTotalRequests, v)
	return u
}

// SetStatus sets the "status" field.
func (u *TempAPIKeyUpsert) SetStatus(v string) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateStatus() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldStatus)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *TempAPIKeyUpsert) SetCreatedBy(v int64) *TempAPIKeyUpsert {
	u.Set(tempapikey.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TempAPIKeyUpsert) UpdateCreatedBy() *TempAPIKeyUpsert {
	u.SetExcluded(tempapikey.FieldCreatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TempAPIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TempAPIKeyUpsertOne) UpdateNewValues() *TempAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tempapikey.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TempAPIKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TempAPIKeyUpsertOne) Ignore() *TempAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TempAPIKeyUpsertOne) DoNothing() *TempAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TempAPIKeyCreate.OnConflict
// documentation for more info.
func (u *TempAPIKeyUpsertOne) Update(set func(*TempAPIKeyUpsert)) *TempAPIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TempAPIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TempAPIKeyUpsertOne) SetUpdatedAt(v time.Time) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateUpdatedAt() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TempAPIKeyUpsertOne) SetDeletedAt(v time.Time) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateDeletedAt() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TempAPIKeyUpsertOne) ClearDeletedAt() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetKey sets the "key" field.
func (u *TempAPIKeyUpsertOne) SetKey(v string) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateKey() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateKey()
	})
}

// SetName sets the "name" field.
func (u *TempAPIKeyUpsertOne) SetName(v string) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateName() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateName()
	})
}

// SetGroupID sets the "group_id" field.
func (u *TempAPIKeyUpsertOne) SetGroupID(v int64) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateGroupID() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateGroupID()
	})
}

// SetValidDays sets the "valid_days" field.
func (u *TempAPIKeyUpsertOne) SetValidDays(v int) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetValidDays(v)
	})
}

// AddValidDays adds v to the "valid_days" field.
func (u *TempAPIKeyUpsertOne) AddValidDays(v int) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.AddValidDays(v)
	})
}

// UpdateValidDays sets the "valid_days" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateValidDays() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateValidDays()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *TempAPIKeyUpsertOne) SetActivatedAt(v time.Time) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateActivatedAt() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateActivatedAt()
	})
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *TempAPIKeyUpsertOne) ClearActivatedAt() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.ClearActivatedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *TempAPIKeyUpsertOne) SetExpiresAt(v time.Time) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateExpiresAt() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *TempAPIKeyUpsertOne) ClearExpiresAt() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.ClearExpiresAt()
	})
}

// SetDailyLimit sets the "daily_limit" field.
func (u *TempAPIKeyUpsertOne) SetDailyLimit(v int) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetDailyLimit(v)
	})
}

// AddDailyLimit adds v to the "daily_limit" field.
func (u *TempAPIKeyUpsertOne) AddDailyLimit(v int) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.AddDailyLimit(v)
	})
}

// UpdateDailyLimit sets the "daily_limit" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateDailyLimit() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateDailyLimit()
	})
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *TempAPIKeyUpsertOne) SetCurrentPeriodStart(v time.Time) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetCurrentPeriodStart(v)
	})
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateCurrentPeriodStart() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateCurrentPeriodStart()
	})
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (u *TempAPIKeyUpsertOne) ClearCurrentPeriodStart() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.ClearCurrentPeriodStart()
	})
}

// SetCurrentPeriodCount sets the "current_period_count" field.
func (u *TempAPIKeyUpsertOne) SetCurrentPeriodCount(v int) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetCurrentPeriodCount(v)
	})
}

// AddCurrentPeriodCount adds v to the "current_period_count" field.
func (u *TempAPIKeyUpsertOne) AddCurrentPeriodCount(v int) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.AddCurrentPeriodCount(v)
	})
}

// UpdateCurrentPeriodCount sets the "current_period_count" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateCurrentPeriodCount() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateCurrentPeriodCount()
	})
}

// SetTotalRequests sets the "total_requests" field.
func (u *TempAPIKeyUpsertOne) SetTotalRequests(v int64) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetTotalRequests(v)
	})
}

// AddTotalRequests adds v to the "total_requests" field.
func (u *TempAPIKeyUpsertOne) AddTotalRequests(v int64) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.AddTotalRequests(v)
	})
}

// UpdateTotalRequests sets the "total_requests" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateTotalRequests() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateTotalRequests()
	})
}

// SetStatus sets the "status" field.
func (u *TempAPIKeyUpsertOne) SetStatus(v string) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateStatus() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TempAPIKeyUpsertOne) SetCreatedBy(v int64) *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TempAPIKeyUpsertOne) UpdateCreatedBy() *TempAPIKeyUpsertOne {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *TempAPIKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TempAPIKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TempAPIKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TempAPIKeyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TempAPIKeyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TempAPIKeyCreateBulk is the builder for creating many TempAPIKey entities in bulk.
type TempAPIKeyCreateBulk struct {
	config
	err      error
	builders []*TempAPIKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the TempAPIKey entities in the database.
func (_c *TempAPIKeyCreateBulk) Save(ctx context.Context) ([]*TempAPIKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TempAPIKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TempAPIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TempAPIKeyCreateBulk) SaveX(ctx context.Context) []*TempAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TempAPIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TempAPIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TempAPIKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TempAPIKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TempAPIKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *TempAPIKeyUpsertBulk {
	_c.conflict = opts
	return &TempAPIKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TempAPIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TempAPIKeyCreateBulk) OnConflictColumns(columns ...string) *TempAPIKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TempAPIKeyUpsertBulk{
		create: _c,
	}
}

// TempAPIKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of TempAPIKey nodes.
type TempAPIKeyUpsertBulk struct {
	create *TempAPIKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TempAPIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TempAPIKeyUpsertBulk) UpdateNewValues() *TempAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tempapikey.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TempAPIKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TempAPIKeyUpsertBulk) Ignore() *TempAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TempAPIKeyUpsertBulk) DoNothing() *TempAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TempAPIKeyCreateBulk.OnConflict
// documentation for more info.
func (u *TempAPIKeyUpsertBulk) Update(set func(*TempAPIKeyUpsert)) *TempAPIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TempAPIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TempAPIKeyUpsertBulk) SetUpdatedAt(v time.Time) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateUpdatedAt() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TempAPIKeyUpsertBulk) SetDeletedAt(v time.Time) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateDeletedAt() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TempAPIKeyUpsertBulk) ClearDeletedAt() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetKey sets the "key" field.
func (u *TempAPIKeyUpsertBulk) SetKey(v string) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateKey() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateKey()
	})
}

// SetName sets the "name" field.
func (u *TempAPIKeyUpsertBulk) SetName(v string) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateName() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateName()
	})
}

// SetGroupID sets the "group_id" field.
func (u *TempAPIKeyUpsertBulk) SetGroupID(v int64) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateGroupID() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateGroupID()
	})
}

// SetValidDays sets the "valid_days" field.
func (u *TempAPIKeyUpsertBulk) SetValidDays(v int) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetValidDays(v)
	})
}

// AddValidDays adds v to the "valid_days" field.
func (u *TempAPIKeyUpsertBulk) AddValidDays(v int) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.AddValidDays(v)
	})
}

// UpdateValidDays sets the "valid_days" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateValidDays() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateValidDays()
	})
}

// SetActivatedAt sets the "activated_at" field.
func (u *TempAPIKeyUpsertBulk) SetActivatedAt(v time.Time) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetActivatedAt(v)
	})
}

// UpdateActivatedAt sets the "activated_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateActivatedAt() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateActivatedAt()
	})
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (u *TempAPIKeyUpsertBulk) ClearActivatedAt() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.ClearActivatedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *TempAPIKeyUpsertBulk) SetExpiresAt(v time.Time) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateExpiresAt() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *TempAPIKeyUpsertBulk) ClearExpiresAt() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.ClearExpiresAt()
	})
}

// SetDailyLimit sets the "daily_limit" field.
func (u *TempAPIKeyUpsertBulk) SetDailyLimit(v int) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetDailyLimit(v)
	})
}

// AddDailyLimit adds v to the "daily_limit" field.
func (u *TempAPIKeyUpsertBulk) AddDailyLimit(v int) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.AddDailyLimit(v)
	})
}

// UpdateDailyLimit sets the "daily_limit" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateDailyLimit() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateDailyLimit()
	})
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *TempAPIKeyUpsertBulk) SetCurrentPeriodStart(v time.Time) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetCurrentPeriodStart(v)
	})
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateCurrentPeriodStart() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateCurrentPeriodStart()
	})
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (u *TempAPIKeyUpsertBulk) ClearCurrentPeriodStart() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.ClearCurrentPeriodStart()
	})
}

// SetCurrentPeriodCount sets the "current_period_count" field.
func (u *TempAPIKeyUpsertBulk) SetCurrentPeriodCount(v int) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetCurrentPeriodCount(v)
	})
}

// AddCurrentPeriodCount adds v to the "current_period_count" field.
func (u *TempAPIKeyUpsertBulk) AddCurrentPeriodCount(v int) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.AddCurrentPeriodCount(v)
	})
}

// UpdateCurrentPeriodCount sets the "current_period_count" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateCurrentPeriodCount() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateCurrentPeriodCount()
	})
}

// SetTotalRequests sets the "total_requests" field.
func (u *TempAPIKeyUpsertBulk) SetTotalRequests(v int64) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetTotalRequests(v)
	})
}

// AddTotalRequests adds v to the "total_requests" field.
func (u *TempAPIKeyUpsertBulk) AddTotalRequests(v int64) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.AddTotalRequests(v)
	})
}

// UpdateTotalRequests sets the "total_requests" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateTotalRequests() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateTotalRequests()
	})
}

// SetStatus sets the "status" field.
func (u *TempAPIKeyUpsertBulk) SetStatus(v string) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateStatus() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TempAPIKeyUpsertBulk) SetCreatedBy(v int64) *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TempAPIKeyUpsertBulk) UpdateCreatedBy() *TempAPIKeyUpsertBulk {
	return u.Update(func(s *TempAPIKeyUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *TempAPIKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TempAPIKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TempAPIKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TempAPIKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
