// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/tempapikey"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TempAPIKey is the model entity for the TempAPIKey schema.
type TempAPIKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// API Key，sk-temp-xxx 格式
	Key string `json:"key,omitempty"`
	// 名称/备注
	Name string `json:"name,omitempty"`
	// 关联分组 ID
	GroupID int64 `json:"group_id,omitempty"`
	// 类型：time_limited（限时限请求数）、quota_only（仅限总额不限时）、time_quota（限时+限每日USD额度）
	KeyType string `json:"key_type,omitempty"`
	// 总额度限制（美元），0 表示不限制，仅 quota_only 类型使用
	TotalQuotaUsd float64 `json:"total_quota_usd,omitempty"`
	// 已消费金额（美元），仅 quota_only 类型使用
	TotalCostUsd float64 `json:"total_cost_usd,omitempty"`
	// 每日 USD 额度上限，仅 time_quota 类型使用
	DailyQuotaUsd float64 `json:"daily_quota_usd,omitempty"`
	// 当前周期已消费 USD，仅 time_quota 类型使用
	CurrentPeriodCostUsd float64 `json:"current_period_cost_usd,omitempty"`
	// 有效天数，从首次使用开始计算
	ValidDays int `json:"valid_days,omitempty"`
	// 首次激活时间
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	// 过期时间
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// 每 24 小时请求限制
	DailyLimit int `json:"daily_limit,omitempty"`
	// 当前 24 小时周期开始时间
	CurrentPeriodStart *time.Time `json:"current_period_start,omitempty"`
	// 当前周期请求次数
	CurrentPeriodCount int `json:"current_period_count,omitempty"`
	// 总请求次数
	TotalRequests int64 `json:"total_requests,omitempty"`
	// 状态：active, inactive, expired
	Status string `json:"status,omitempty"`
	// 创建者 ID（管理员）
	CreatedBy int64 `json:"created_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TempAPIKeyQuery when eager-loading is set.
	Edges        TempAPIKeyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TempAPIKeyEdges holds the relations/edges for other nodes in the graph.
type TempAPIKeyEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TempAPIKeyEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TempAPIKeyEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e TempAPIKeyEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[2] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TempAPIKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tempapikey.FieldTotalQuotaUsd, tempapikey.FieldTotalCostUsd, tempapikey.FieldDailyQuotaUsd, tempapikey.FieldCurrentPeriodCostUsd:
			values[i] = new(sql.NullFloat64)
		case tempapikey.FieldID, tempapikey.FieldGroupID, tempapikey.FieldValidDays, tempapikey.FieldDailyLimit, tempapikey.FieldCurrentPeriodCount, tempapikey.FieldTotalRequests, tempapikey.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case tempapikey.FieldKey, tempapikey.FieldName, tempapikey.FieldKeyType, tempapikey.FieldStatus:
			values[i] = new(sql.NullString)
		case tempapikey.FieldCreatedAt, tempapikey.FieldUpdatedAt, tempapikey.FieldDeletedAt, tempapikey.FieldActivatedAt, tempapikey.FieldExpiresAt, tempapikey.FieldCurrentPeriodStart:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TempAPIKey fields.
func (_m *TempAPIKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tempapikey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case tempapikey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tempapikey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case tempapikey.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case tempapikey.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case tempapikey.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tempapikey.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case tempapikey.FieldKeyType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_type", values[i])
			} else if value.Valid {
				_m.KeyType = value.String
			}
		case tempapikey.FieldTotalQuotaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_quota_usd", values[i])
			} else if value.Valid {
				_m.TotalQuotaUsd = value.Float64
			}
		case tempapikey.FieldTotalCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost_usd", values[i])
			} else if value.Valid {
				_m.TotalCostUsd = value.Float64
			}
		case tempapikey.FieldDailyQuotaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_quota_usd", values[i])
			} else if value.Valid {
				_m.DailyQuotaUsd = value.Float64
			}
		case tempapikey.FieldCurrentPeriodCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field current_period_cost_usd", values[i])
			} else if value.Valid {
				_m.CurrentPeriodCostUsd = value.Float64
			}
		case tempapikey.FieldValidDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field valid_days", values[i])
			} else if value.Valid {
				_m.ValidDays = int(value.Int64)
			}
		case tempapikey.FieldActivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field activated_at", values[i])
			} else if value.Valid {
				_m.ActivatedAt = new(time.Time)
				*_m.ActivatedAt = value.Time
			}
		case tempapikey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case tempapikey.FieldDailyLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit", values[i])
			} else if value.Valid {
				_m.DailyLimit = int(value.Int64)
			}
		case tempapikey.FieldCurrentPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field current_period_start", values[i])
			} else if value.Valid {
				_m.CurrentPeriodStart = new(time.Time)
				*_m.CurrentPeriodStart = value.Time
			}
		case tempapikey.FieldCurrentPeriodCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_period_count", values[i])
			} else if value.Valid {
				_m.CurrentPeriodCount = int(value.Int64)
			}
		case tempapikey.FieldTotalRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_requests", values[i])
			} else if value.Valid {
				_m.TotalRequests = value.Int64
			}
		case tempapikey.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case tempapikey.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TempAPIKey.
// This includes values selected through modifiers, order, etc.
func (_m *TempAPIKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the TempAPIKey entity.
func (_m *TempAPIKey) QueryGroup() *GroupQuery {
	return NewTempAPIKeyClient(_m.config).QueryGroup(_m)
}

// QueryCreator queries the "creator" edge of the TempAPIKey entity.
func (_m *TempAPIKey) QueryCreator() *UserQuery {
	return NewTempAPIKeyClient(_m.config).QueryCreator(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the TempAPIKey entity.
func (_m *TempAPIKey) QueryUsageLogs() *UsageLogQuery {
	return NewTempAPIKeyClient(_m.config).QueryUsageLogs(_m)
}

// Update returns a builder for updating this TempAPIKey.
// Note that you need to call TempAPIKey.Unwrap() before calling this method if this TempAPIKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TempAPIKey) Update() *TempAPIKeyUpdateOne {
	return NewTempAPIKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TempAPIKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TempAPIKey) Unwrap() *TempAPIKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TempAPIKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TempAPIKey) String() string {
	var builder strings.Builder
	builder.WriteString("TempAPIKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("key_type=")
	builder.WriteString(_m.KeyType)
	builder.WriteString(", ")
	builder.WriteString("total_quota_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalQuotaUsd))
	builder.WriteString(", ")
	builder.WriteString("total_cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCostUsd))
	builder.WriteString(", ")
	builder.WriteString("daily_quota_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyQuotaUsd))
	builder.WriteString(", ")
	builder.WriteString("current_period_cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentPeriodCostUsd))
	builder.WriteString(", ")
	builder.WriteString("valid_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidDays))
	builder.WriteString(", ")
	if v := _m.ActivatedAt; v != nil {
		builder.WriteString("activated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("daily_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyLimit))
	builder.WriteString(", ")
	if v := _m.CurrentPeriodStart; v != nil {
		builder.WriteString("current_period_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("current_period_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentPeriodCount))
	builder.WriteString(", ")
	builder.WriteString("total_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalRequests))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// TempAPIKeys is a parsable slice of TempAPIKey.
type TempAPIKeys []*TempAPIKey
