// Code generated by ent, DO NOT EDIT.

package tempapikey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldDeletedAt, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldKey, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldName, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldGroupID, v))
}

// ValidDays applies equality check predicate on the "valid_days" field. It's identical to ValidDaysEQ.
func ValidDays(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldValidDays, v))
}

// ActivatedAt applies equality check predicate on the "activated_at" field. It's identical to ActivatedAtEQ.
func ActivatedAt(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldActivatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// DailyLimit applies equality check predicate on the "daily_limit" field. It's identical to DailyLimitEQ.
func DailyLimit(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldDailyLimit, v))
}

// CurrentPeriodStart applies equality check predicate on the "current_period_start" field. It's identical to CurrentPeriodStartEQ.
func CurrentPeriodStart(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldCurrentPeriodStart, v))
}

// CurrentPeriodCount applies equality check predicate on the "current_period_count" field. It's identical to CurrentPeriodCountEQ.
func CurrentPeriodCount(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldCurrentPeriodCount, v))
}

// TotalRequests applies equality check predicate on the "total_requests" field. It's identical to TotalRequestsEQ.
func TotalRequests(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldTotalRequests, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldStatus, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotNull(FieldDeletedAt))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldContainsFold(FieldKey, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldContainsFold(FieldName, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldGroupID, vs...))
}

// ValidDaysEQ applies the EQ predicate on the "valid_days" field.
func ValidDaysEQ(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldValidDays, v))
}

// ValidDaysNEQ applies the NEQ predicate on the "valid_days" field.
func ValidDaysNEQ(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldValidDays, v))
}

// ValidDaysIn applies the In predicate on the "valid_days" field.
func ValidDaysIn(vs ...int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldValidDays, vs...))
}

// ValidDaysNotIn applies the NotIn predicate on the "valid_days" field.
func ValidDaysNotIn(vs ...int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldValidDays, vs...))
}

// ValidDaysGT applies the GT predicate on the "valid_days" field.
func ValidDaysGT(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldValidDays, v))
}

// ValidDaysGTE applies the GTE predicate on the "valid_days" field.
func ValidDaysGTE(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldValidDays, v))
}

// ValidDaysLT applies the LT predicate on the "valid_days" field.
func ValidDaysLT(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldValidDays, v))
}

// ValidDaysLTE applies the LTE predicate on the "valid_days" field.
func ValidDaysLTE(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldValidDays, v))
}

// ActivatedAtEQ applies the EQ predicate on the "activated_at" field.
func ActivatedAtEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldActivatedAt, v))
}

// ActivatedAtNEQ applies the NEQ predicate on the "activated_at" field.
func ActivatedAtNEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldActivatedAt, v))
}

// ActivatedAtIn applies the In predicate on the "activated_at" field.
func ActivatedAtIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldActivatedAt, vs...))
}

// ActivatedAtNotIn applies the NotIn predicate on the "activated_at" field.
func ActivatedAtNotIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldActivatedAt, vs...))
}

// ActivatedAtGT applies the GT predicate on the "activated_at" field.
func ActivatedAtGT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldActivatedAt, v))
}

// ActivatedAtGTE applies the GTE predicate on the "activated_at" field.
func ActivatedAtGTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldActivatedAt, v))
}

// ActivatedAtLT applies the LT predicate on the "activated_at" field.
func ActivatedAtLT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldActivatedAt, v))
}

// ActivatedAtLTE applies the LTE predicate on the "activated_at" field.
func ActivatedAtLTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldActivatedAt, v))
}

// ActivatedAtIsNil applies the IsNil predicate on the "activated_at" field.
func ActivatedAtIsNil() predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIsNull(FieldActivatedAt))
}

// ActivatedAtNotNil applies the NotNil predicate on the "activated_at" field.
func ActivatedAtNotNil() predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotNull(FieldActivatedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotNull(FieldExpiresAt))
}

// DailyLimitEQ applies the EQ predicate on the "daily_limit" field.
func DailyLimitEQ(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldDailyLimit, v))
}

// DailyLimitNEQ applies the NEQ predicate on the "daily_limit" field.
func DailyLimitNEQ(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldDailyLimit, v))
}

// DailyLimitIn applies the In predicate on the "daily_limit" field.
func DailyLimitIn(vs ...int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldDailyLimit, vs...))
}

// DailyLimitNotIn applies the NotIn predicate on the "daily_limit" field.
func DailyLimitNotIn(vs ...int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldDailyLimit, vs...))
}

// DailyLimitGT applies the GT predicate on the "daily_limit" field.
func DailyLimitGT(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldDailyLimit, v))
}

// DailyLimitGTE applies the GTE predicate on the "daily_limit" field.
func DailyLimitGTE(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldDailyLimit, v))
}

// DailyLimitLT applies the LT predicate on the "daily_limit" field.
func DailyLimitLT(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldDailyLimit, v))
}

// DailyLimitLTE applies the LTE predicate on the "daily_limit" field.
func DailyLimitLTE(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldDailyLimit, v))
}

// CurrentPeriodStartEQ applies the EQ predicate on the "current_period_start" field.
func CurrentPeriodStartEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldCurrentPeriodStart, v))
}

// CurrentPeriodStartNEQ applies the NEQ predicate on the "current_period_start" field.
func CurrentPeriodStartNEQ(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldCurrentPeriodStart, v))
}

// CurrentPeriodStartIn applies the In predicate on the "current_period_start" field.
func CurrentPeriodStartIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldCurrentPeriodStart, vs...))
}

// CurrentPeriodStartNotIn applies the NotIn predicate on the "current_period_start" field.
func CurrentPeriodStartNotIn(vs ...time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldCurrentPeriodStart, vs...))
}

// CurrentPeriodStartGT applies the GT predicate on the "current_period_start" field.
func CurrentPeriodStartGT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldCurrentPeriodStart, v))
}

// CurrentPeriodStartGTE applies the GTE predicate on the "current_period_start" field.
func CurrentPeriodStartGTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldCurrentPeriodStart, v))
}

// CurrentPeriodStartLT applies the LT predicate on the "current_period_start" field.
func CurrentPeriodStartLT(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldCurrentPeriodStart, v))
}

// CurrentPeriodStartLTE applies the LTE predicate on the "current_period_start" field.
func CurrentPeriodStartLTE(v time.Time) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldCurrentPeriodStart, v))
}

// CurrentPeriodStartIsNil applies the IsNil predicate on the "current_period_start" field.
func CurrentPeriodStartIsNil() predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIsNull(FieldCurrentPeriodStart))
}

// CurrentPeriodStartNotNil applies the NotNil predicate on the "current_period_start" field.
func CurrentPeriodStartNotNil() predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotNull(FieldCurrentPeriodStart))
}

// CurrentPeriodCountEQ applies the EQ predicate on the "current_period_count" field.
func CurrentPeriodCountEQ(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldCurrentPeriodCount, v))
}

// CurrentPeriodCountNEQ applies the NEQ predicate on the "current_period_count" field.
func CurrentPeriodCountNEQ(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldCurrentPeriodCount, v))
}

// CurrentPeriodCountIn applies the In predicate on the "current_period_count" field.
func CurrentPeriodCountIn(vs ...int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldCurrentPeriodCount, vs...))
}

// CurrentPeriodCountNotIn applies the NotIn predicate on the "current_period_count" field.
func CurrentPeriodCountNotIn(vs ...int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldCurrentPeriodCount, vs...))
}

// CurrentPeriodCountGT applies the GT predicate on the "current_period_count" field.
func CurrentPeriodCountGT(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldCurrentPeriodCount, v))
}

// CurrentPeriodCountGTE applies the GTE predicate on the "current_period_count" field.
func CurrentPeriodCountGTE(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldCurrentPeriodCount, v))
}

// CurrentPeriodCountLT applies the LT predicate on the "current_period_count" field.
func CurrentPeriodCountLT(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldCurrentPeriodCount, v))
}

// CurrentPeriodCountLTE applies the LTE predicate on the "current_period_count" field.
func CurrentPeriodCountLTE(v int) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldCurrentPeriodCount, v))
}

// TotalRequestsEQ applies the EQ predicate on the "total_requests" field.
func TotalRequestsEQ(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldTotalRequests, v))
}

// TotalRequestsNEQ applies the NEQ predicate on the "total_requests" field.
func TotalRequestsNEQ(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldTotalRequests, v))
}

// TotalRequestsIn applies the In predicate on the "total_requests" field.
func TotalRequestsIn(vs ...int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldTotalRequests, vs...))
}

// TotalRequestsNotIn applies the NotIn predicate on the "total_requests" field.
func TotalRequestsNotIn(vs ...int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldTotalRequests, vs...))
}

// TotalRequestsGT applies the GT predicate on the "total_requests" field.
func TotalRequestsGT(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldTotalRequests, v))
}

// TotalRequestsGTE applies the GTE predicate on the "total_requests" field.
func TotalRequestsGTE(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldTotalRequests, v))
}

// TotalRequestsLT applies the LT predicate on the "total_requests" field.
func TotalRequestsLT(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldTotalRequests, v))
}

// TotalRequestsLTE applies the LTE predicate on the "total_requests" field.
func TotalRequestsLTE(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldTotalRequests, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.TempAPIKey {
	return predicate.TempAPIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.TempAPIKey {
	return predicate.TempAPIKey(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.TempAPIKey {
	return predicate.TempAPIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.TempAPIKey {
	return predicate.TempAPIKey(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.TempAPIKey {
	return predicate.TempAPIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.TempAPIKey {
	return predicate.TempAPIKey(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TempAPIKey) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TempAPIKey) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TempAPIKey) predicate.TempAPIKey {
	return predicate.TempAPIKey(sql.NotPredicates(p))
}
